### PR TITLE
feat:基本短链接功能

### PR DESCRIPTION
**Pull request by mtnbgx**

### CODE REVIEW

**Comment by gao-sun** [comment]
taking a look

**Comment by gao-sun** [comment]
please drop your contact info when convenient, thanks

**Comment by mtnbgx** [comment]
> 请在方便时删除您的联系信息，谢谢

d2VjaGF077yad3hfMTE1NjkwOTc4OQ==

**Comment by mtnbgx** [comment]
> please drop your contact info when convenient, thanks

d2VjaGF077yad3hfMTE1NjkwOTc4OQ==

**Comment by gao-sun** [comment]
@mtnbgx you can safely delete your info now

**Comment by gao-sun** [comment]
@mtnbgx sorry, would you mind to leave your email address instead?

**Comment by mtnbgx** [comment]
> @mtnbgx sorry, would you mind to leave your email address instead?

MTE1NjkwOTc4OUBxcS5jb20=

**Comment by gao-sun** [comment]
thanks. you can safely delete your info now.

**Comment by gao-sun** [comment]
message sent to your email

**Pull request closed without merging**
