### PR TITLE
提交 Swift 作业

### PR DESCRIPTION
**Pull request by qiukun**
PTAL

### CODE REVIEW

**Comment by gao-sun** [comment]
mind to remove third party source code and use a mainstream dependency management tool instead?

**Comment by qiukun** [comment]
> mind to remove third party source code and use a mainstream dependency management tool instead?

@gao-sun Sure. Noise is now reduced.

**Comment by gao-sun** [comment]
2 comments from team:
1. 能不能将 View 改成 SwiftUI （代码中还有 UIKit）
2. Apply MVVM pattern (with Combine)

**Comment by qiukun** [comment]
我试试

**Comment by qiukun** [comment]
@gao-sun PTAL

**Pull request closed without merging**
