### PR TITLE
solution to short url question in Typescript

### PR DESCRIPTION
**Pull request by GingerAndOnion**

### CODE REVIEW

**Comment by gao-sun** [comment]
great work. please leave your contact info when convenient.

**Comment by gao-sun** [comment]
btw email address is preferred, thanks

**Comment by GingerAndOnion** [comment]
thanks for quick responding. sean.gao@gmail.com or sgao0311@163.com, either can reach me.  thanks,

**Comment by gao-sun** [comment]
message sent to your address. you can safely delete your info now.

**Pull request closed without merging**
